apiVersion: v1
kind: Secret
metadata:
  name: platform-application-insights
type: Opaque
stringData:
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ required "applicationInsightsConnectionString must be supplied by Terraform" .Values.applicationInsightsConnectionString | quote }}
